config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :admin, controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :teacher, controllers: {
    sessions: 'teacher/sessions'
  }
  devise_for :user

  root 'lessons#index'
  resources :lessons, only: :index do
    collection do
      get :reserved
    end
    resource :reservation, only: :create
  end
  resources :products, only: :index do
    resource :checkout, only: :new do
      member do
        get :success
        get :cancel
      end
    end
  end

  namespace :admin do
    root 'teachers#index'
    resources :teachers, except: :show do
      member do
        get :masquerade
      end
    end
  end

  namespace :teacher do
    root 'lessons#index'
    resource :profile, only: %i[edit update]
    resources :lessons do
      collection do
        get :reserved
      end
    end
  end

  namespace :stripe do
    mount StripeEvent::Engine, at: 'webhook'
  end
end

app/views/layouts/admin/_header.html.haml
%header.bg-primary
  .container
    %nav.navbar.navbar-dark.navbar-expand-lg
      = link_to '[管理者] Online Language Lesson', admin_root_path, class: 'navbar-brand'
      %button.navbar-toggler{ type: 'button',
                              data: { toggle: 'collapse', target: '#navbar' },
                              aria: { controls: 'navbar', expanded: 'false', label: 'Toggle navigation' }}
        %span.navbar-toggler-icon
      #navbar.collapse.navbar-collapse
        %ul.navbar-nav.ml-auto
          - if admin_signed_in?
            %li.nav-item= active_link_to '講師一覧', admin_teachers_path, class: 'nav-link'
            %li.nav-item= active_link_to 'ログアウト', destroy_admin_session_path, class: 'nav-link', method: :delete
          - else
            %li.nav-item= active_link_to 'ログイン', new_admin_session_path, class: 'nav-link'

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }/
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
    %title [管理者] Online Language Lesson
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/admin/header'
    .container
      = render 'layouts/flashes'
      = yield